name: CI/CD Pipeline

on:
  push:
  pull_request:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies 
        run: npm ci

      - name: Build production build 
        run: npm run build

      - name: Deploy to server using rsync
        uses: up9cloud/action-rsync@master
        env:
          USER: deploy-user
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /var/www/business-designer-backend/
          SOURCE: './'
          ARGS: '-avz --delete --exclude=/.git/ --exclude=/.github/ --exclude=/node_modules/'
          RUN_SCRIPT_ON: 'target'
          POST_SCRIPT: 'cd /var/www/business-designer-backend/ && docker compose up -d --build'